version: '3.9'

networks:
  restobook-net:

volumes:
  restobook-data:
  restobook-pgadmin-servers:

services:
  server:
    build:
      context: .
      target: development
    ports:
      - 8081:8080
    depends_on:
      - restobook-db
    environment:
      POSTGRES_URL: jdbc:postgresql://restobook-db:5432/${POSTGRES_DB}

  restobook-db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - restobook-net
    volumes:
      - restobook-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${PG_ROOT_USER}'" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: elestio/pgadmin:REL-8_3
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - restobook-net
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - restobook-pgadmin-servers:/pgadmin4/servers.json
    depends_on:
      - restobook-db