server:
  port: 8181
  servlet:
    context-path: /restobook-api

spring:
  application.name: restobook_backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}
    schemas: public

  jwt:
    auth:
      converter:
        resource-id: restobook-rest-api
        admin-id: admin-cli
        principle-attribute: preferred_username

keycloak:
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  adminRealm: ${KEYCLOAK_ADMIN_REALM}
  adminClientId: ${KEYCLOAK_ADMIN_CLIENT}
  username: ${KEYCLOAK_ADMIN}
  password: ${KEYCLOAK_ADMIN_PASSWORD}
  masterIssuer: ${KEYCLOAK_MASTER_ISSUER}
  restaurantIssuer: ${KEYCLOAK_RESTAURANT_ISSUER}
